#!/usr/bin/env node
// Regenerates every place blog metadata is duplicated, from the single source of
// truth in src/data/blogPosts.ts.
//
//   node scripts/sync-seo.mjs [--check]
//
// Targets:
//   public/sitemap.xml       — fully regenerated
//   public/llms.txt          — "## Blog articles" section, missing entries appended
//   server.js BLOG_META      — missing entries appended (title/description for <head>)
//   server.js BLOG_DATES     — missing entries appended (BlogPosting schema dates)
//   server.js BLOG_SECTIONS_DATA — missing entries appended (raw HTML body for non-JS crawlers)
//
// server.js blocks are *appended to*, never rewritten: several existing entries
// have hand-tuned SEO titles and bodies that deliberately differ from the client
// copy, and silently overwriting them would churn 110 live URLs. New posts get
// their entries generated; drift on existing ones is reported, not "fixed".
//
// Run with --check to fail (exit 1) instead of writing — useful in CI.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Node >= 22.18 strips TypeScript types on import, so blogPosts.ts loads directly.
const { BLOG_POSTS } = await import('../src/data/blogPosts.ts');

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK_ONLY = process.argv.includes('--check');
const ORIGIN = 'https://stopbiting.today';

const problems = [];
const changes = [];

// ─── Core (non-blog) pages ───────────────────────────────────────────────────
// Must stay in sync with KNOWN_ROUTES in server.js and the routes in src/App.tsx.
const CORE_PAGES = [
  { path: '/',                                  changefreq: 'weekly',  priority: '1.0' },
  { path: '/blog',                              changefreq: 'weekly',  priority: '0.9' },
  { path: '/how-it-works',                      changefreq: 'monthly', priority: '0.8' },
  { path: '/about',                             changefreq: 'monthly', priority: '0.6' },
  { path: '/compare/bitter-polish-alternative', changefreq: 'monthly', priority: '0.8' },
  { path: '/compare/habit-tracking-apps',       changefreq: 'monthly', priority: '0.8' },
  { path: '/solutions/for-desk-workers',        changefreq: 'monthly', priority: '0.7' },
  { path: '/solutions/for-adhd',                changefreq: 'monthly', priority: '0.7' },
  { path: '/solutions/for-gamers',              changefreq: 'monthly', priority: '0.7' },
  { path: '/privacy',                           changefreq: 'yearly',  priority: '0.3' },
  { path: '/terms-and-conditions',              changefreq: 'yearly',  priority: '0.3' },
  { path: '/refund-policy',                     changefreq: 'yearly',  priority: '0.3' },
];

// ─── Validate the source data ────────────────────────────────────────────────
const seenSlugs = new Set();
for (const post of BLOG_POSTS) {
  if (seenSlugs.has(post.slug)) problems.push(`duplicate slug: ${post.slug}`);
  seenSlugs.add(post.slug);
  if (!/^[a-z0-9-]+$/.test(post.slug)) problems.push(`slug is not URL-safe: ${post.slug}`);
  if (post.dateModified < post.datePublished) {
    problems.push(`dateModified precedes datePublished: ${post.slug}`);
  }
}

// `description` doubles as the on-page standfirst and, for posts generated into
// server.js, as the meta description. Only the latter has a length budget — so
// this is checked below, against the entries actually written to BLOG_META.
function checkMetaLength(post) {
  const title = post.seoTitle ?? post.title;
  if (post.description.length > 165) {
    problems.push(`meta description ${post.description.length} chars (>165, truncated in SERPs): ${post.slug}`);
  }
  // server.js keeps titles inside a 60-char budget, dropping the " | Stop Biting"
  // suffix before it will cut any words. Under 46 chars keeps the brand; over 60
  // still loses the tail, so flag that as worth an explicit seoTitle.
  if (title.length > 60) {
    problems.push(`meta title ${title.length} chars (>60, server trims the tail): ${post.slug} — set seoTitle`);
  }
}

// ─── public/sitemap.xml — full regeneration ──────────────────────────────────
{
  const newest = BLOG_POSTS.reduce((max, p) => (p.dateModified > max ? p.dateModified : max), '2026-01-01');

  const urls = [
    ...CORE_PAGES.map(p => ({
      loc: `${ORIGIN}${p.path}`,
      // Hub pages gain freshness whenever any article is updated.
      lastmod: p.path === '/' || p.path === '/blog' ? newest : '2026-04-28',
      changefreq: p.changefreq,
      priority: p.priority,
    })),
    ...BLOG_POSTS.map(post => ({
      loc: `${ORIGIN}/blog/${post.slug}`,
      lastmod: post.dateModified,
      changefreq: 'monthly',
      priority: '0.7',
    })),
  ];

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/sync-seo.mjs — do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    '',
    ...urls.flatMap(u => [
      '  <url>',
      `    <loc>${u.loc}</loc>`,
      `    <lastmod>${u.lastmod}</lastmod>`,
      `    <changefreq>${u.changefreq}</changefreq>`,
      `    <priority>${u.priority}</priority>`,
      '  </url>',
      '',
    ]),
    '</urlset>',
    '',
  ].join('\n');

  writeIfChanged(join(ROOT, 'public/sitemap.xml'), xml, `sitemap.xml (${urls.length} URLs)`);
}

// ─── server.js COMPARE_CONTENT — full regeneration ───────────────────────────
// The /compare/* and /solutions/* pages render their body from
// src/data/comparePages.ts once React boots. Crawlers that never run JS saw
// only a <title> and meta description. This mirrors the same data into
// server.js so it can inject the body, and is fully regenerated rather than
// appended to, so the two cannot drift.
{
  const { PAGE_MAP } = await import('../src/data/comparePages.ts');

  const entries = Object.entries(PAGE_MAP).map(([path, get]) => {
    const c = get();
    const sections = c.sections
      .map(s => `        { heading: ${js(s.heading)}, body: ${js(s.body)} },`)
      .join('\n');
    return [
      `    '${path}': {`,
      `      title: ${js(c.title)},`,
      `      subtitle: ${js(c.subtitle)},`,
      `      intro: ${js(c.intro)},`,
      '      sections: [',
      sections,
      '      ],',
      '    },',
    ].join('\n');
  }).join('\n');

  const block = `  const COMPARE_CONTENT = {\n${entries}\n  };\n`;

  const source = safeRead(join(ROOT, 'server.js'));
  if (source === null) {
    problems.push('server.js: could not read — COMPARE_CONTENT skipped');
  } else {
    const re = /  const COMPARE_CONTENT = \{[\s\S]*?\n  \};\n/;
    if (!re.test(source)) {
      problems.push('server.js: could not locate "const COMPARE_CONTENT = {" — skipped');
    } else {
      const next = source.replace(re, () => block);
      writeIfChanged(join(ROOT, 'server.js'), next,
        `server.js COMPARE_CONTENT (${Object.keys(PAGE_MAP).length} pages)`);
    }
  }
}

// ─── src/data/blogIndex.ts — full regeneration ───────────────────────────────
// blogPosts.ts carries every article body — ~700KB of source. The landing page
// and the blog index only ever read titles, tags, descriptions and reading
// times, so they import this metadata-only mirror instead and never drag the
// bodies into their bundle chunk. Fully regenerated, so it cannot drift.
{
  const entries = BLOG_POSTS.map(p => [
    '  {',
    `    slug: ${js(p.slug)},`,
    `    title: ${js(p.title)},`,
    `    description: ${js(p.description)},`,
    `    tag: ${js(p.tag)},`,
    `    readingMinutes: ${p.readingMinutes},`,
    `    datePublished: ${js(p.datePublished)},`,
    `    dateModified: ${js(p.dateModified)},`,
    '  },',
  ].join('\n')).join('\n');

  const ts = [
    '// Generated by scripts/sync-seo.mjs — do not edit by hand.',
    '//',
    '// Metadata-only mirror of BLOG_POSTS. Import this rather than',
    '// ./blogPosts anywhere the article bodies are not actually rendered:',
    '// blogPosts.ts is one large array literal, so a bundler cannot tree-shake',
    '// the `sections` field away and any importer pays for every article body.',
    '',
    'export interface BlogPostMeta {',
    '  slug: string;',
    '  title: string;',
    '  description: string;',
    '  tag: string;',
    '  readingMinutes: number;',
    '  datePublished: string;',
    '  dateModified: string;',
    '}',
    '',
    'export const BLOG_INDEX: BlogPostMeta[] = [',
    entries,
    '];',
    '',
  ].join('\n');

  writeIfChanged(
    join(ROOT, 'src/data/blogIndex.ts'),
    ts,
    `blogIndex.ts (${BLOG_POSTS.length} posts)`,
  );
}

// ─── server.js — append entries for slugs that are missing ───────────────────
{
  const serverPath = join(ROOT, 'server.js');
  let server = readFileSync(serverPath, 'utf8');

  server = appendToBlock(server, 'BLOG_META', post => {
    checkMetaLength(post);
    const title = post.seoTitle ?? post.title;
    return `    ${js(post.slug)}: {\n`
      + `      title: ${js(title)},\n`
      + `      description: ${js(post.description)},\n`
      + `    },`;
  });

  server = appendToBlock(server, 'BLOG_DATES', post =>
    `    ${js(post.slug)}: { datePublished: ${js(post.datePublished)}, dateModified: ${js(post.dateModified)} },`);

  server = appendToBlock(server, 'BLOG_SECTIONS_DATA', post => {
    const sections = post.sections.map(s => {
      const parts = [`heading: ${js(s.heading)}`, `body: ${js(s.body)}`];
      if (s.list?.length) parts.push(`list: [${s.list.map(js).join(', ')}]`);
      if (s.html) parts.push(`html: ${js(s.html)}`);
      return `      { ${parts.join(', ')} },`;
    });
    return `    ${js(post.slug)}: [\n${sections.join('\n')}\n    ],`;
  });

  writeIfChanged(serverPath, server, 'server.js');
}

// ─── public/llms.txt — append missing blog entries ───────────────────────────
{
  const llmsPath = join(ROOT, 'public/llms.txt');
  const llms = readFileSync(llmsPath, 'utf8');
  const lines = llms.split('\n');

  const start = lines.findIndex(l => l.trim() === '## Blog articles');
  if (start === -1) {
    problems.push('llms.txt: "## Blog articles" section not found — skipped');
  } else {
    let end = lines.findIndex((l, i) => i > start && l.startsWith('## '));
    if (end === -1) end = lines.length;

    const listed = new Set();
    for (let i = start; i < end; i++) {
      const m = lines[i].match(/\/blog\/([a-z0-9-]+)\)/);
      if (m) listed.add(m[1]);
    }

    const missing = BLOG_POSTS.filter(p => !listed.has(p.slug));
    if (missing.length) {
      // Trailing blank lines sit between the last entry and the next "## " heading.
      let insertAt = end;
      while (insertAt > start && lines[insertAt - 1].trim() === '') insertAt--;

      const added = missing.map(p =>
        `- [${p.title}](${ORIGIN}/blog/${p.slug}): ${firstSentence(p.description)}`);
      lines.splice(insertAt, 0, ...added);

      writeIfChanged(llmsPath, lines.join('\n'), `llms.txt (+${missing.length} entries)`);
    }
  }
}

// ─── server.js BLOG_META vs client titles — report only ──────────────────────
// server.js puts BLOG_META's title in the HTML, then BlogPost overwrites
// document.title with `seoTitle ?? title` from blogPosts.ts on mount. Google
// indexes the *rendered* title, so wherever these two disagree the hand-tuned
// server title is the one that loses. Reported rather than reconciled: which
// wording should win is a content call.
{
  const source = safeRead(join(ROOT, 'server.js')) ?? '';
  const start = source.indexOf('  const BLOG_META = {');
  const end = source.indexOf('\n  };\n', start);
  const block = start === -1 ? '' : source.slice(start, end);

  // Slice the block at each slug key, then read the title out of that entry
  // alone. Entries are hand-edited and use all three quote styles — single,
  // double and backtick — so the quote character has to be captured, not
  // assumed, and the entry boundary comes from the next key rather than from
  // guessing at indentation.
  const keys = [...block.matchAll(/^ {4}['"`]([a-z0-9-]+)['"`]:/gm)]
    .map(m => ({ slug: m[1], at: m.index }));

  const serverTitles = new Map();
  keys.forEach(({ slug, at }, i) => {
    const entry = block.slice(at, i + 1 < keys.length ? keys[i + 1].at : block.length);
    const t = /title:\s*(['"`])((?:\\.|(?!\1)[\s\S])*)\1/.exec(entry);
    if (t) serverTitles.set(slug, t[2].replace(/\\(['"`\\])/g, '$1'));
  });

  const serverTitleFor = slug => serverTitles.get(slug) ?? null;

  const diverging = [];
  let unreadable = 0;
  for (const post of BLOG_POSTS) {
    const serverTitle = serverTitleFor(post.slug);
    if (serverTitle === null) { unreadable++; continue; }
    const clientTitle = post.seoTitle ?? post.title;
    if (serverTitle !== clientTitle) diverging.push({ slug: post.slug, serverTitle, clientTitle });
  }

  if (unreadable) {
    problems.push(`BLOG_META: could not read a title for ${unreadable} slug(s)`);
  }
  if (diverging.length) {
    problems.push(
      `${diverging.length} post(s) where the rendered title differs from BLOG_META — ` +
      'the server title is discarded on hydration. Align blogPosts.ts seoTitle ' +
      'with BLOG_META, or drop the BLOG_META override:',
    );
    for (const d of diverging) {
      problems.push(`    ${d.slug}\n        server: ${d.serverTitle}\n        client: ${d.clientTitle}`);
    }
  }
}

// ─── Report ──────────────────────────────────────────────────────────────────
if (problems.length) {
  console.error('\nProblems found:');
  for (const p of problems) console.error(`  ! ${p}`);
}
if (!changes.length && !problems.length) {
  console.log(`SEO data in sync — ${BLOG_POSTS.length} posts, nothing to do.`);
}
if (CHECK_ONLY && (changes.length || problems.length)) {
  console.error('\n--check: SEO data is out of date. Run `node scripts/sync-seo.mjs`.');
  process.exit(1);
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// JS string literal. JSON.stringify is a valid subset of JS string syntax and
// escapes quotes, backslashes and newlines correctly.
function js(str) {
  return JSON.stringify(str);
}

function firstSentence(text) {
  const m = text.match(/^.*?[.!?](?=\s|$)/);
  return (m ? m[0] : text).trim();
}

// Finds `  const NAME = {` … matching `  };` and appends entries for any post
// whose slug is not already a key. Existing entries are left untouched.
function appendToBlock(source, name, render) {
  const startMarker = `  const ${name} = {\n`;
  const startIdx = source.indexOf(startMarker);
  if (startIdx === -1) {
    problems.push(`server.js: could not locate "const ${name} = {" — skipped`);
    return source;
  }

  const bodyStart = startIdx + startMarker.length;
  const endIdx = source.indexOf('\n  };\n', bodyStart);
  if (endIdx === -1) {
    problems.push(`server.js: could not locate the end of ${name} — skipped`);
    return source;
  }

  const body = source.slice(bodyStart, endIdx);
  const present = new Set([...body.matchAll(/^ {4}'([a-z0-9-]+)':|^ {4}"([a-z0-9-]+)":/gm)]
    .map(m => m[1] ?? m[2]));

  for (const slug of present) {
    if (!seenSlugs.has(slug)) {
      problems.push(`server.js ${name}: entry for "${slug}" has no matching post in blogPosts.ts (stale?)`);
    }
  }

  const missing = BLOG_POSTS.filter(p => !present.has(p.slug));
  if (!missing.length) return source;

  const addition = '\n' + missing.map(render).join('\n');
  changes.push(`server.js ${name}: +${missing.length} entries`);
  return source.slice(0, endIdx) + addition + source.slice(endIdx);
}

function writeIfChanged(path, content, label) {
  const previous = safeRead(path);
  if (previous === content) return;
  changes.push(label);
  if (!CHECK_ONLY) writeFileSync(path, content);
  console.log(`${CHECK_ONLY ? 'stale' : 'wrote'}: ${label}`);
}

function safeRead(path) {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}
